service: sls-site

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 profile: admin-aws2

functions:
 api:
   handler: lambda.express
   events:
     - http: GET /{proxy+}
     - http: GET /

custom:
  apigwBinary:
    types:           #list of mime-types
      - '*/*'
  includeDependencies:
    always:
      - 'src/lib/**'

package:
  exclude:
    - 'node_modules/**'

plugins:
  - serverless-apigw-binary
  - serverless-plugin-include-dependencies

